import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { clearCustomerSession, customerApi } from "../auth/customerAuth";
import { useCustomer } from "../context/CustomerContext";
import { PublicPageLayout } from "../components/PublicPageLayout";

export default function CustomerAuth() {
  const location = useLocation(); const navigate = useNavigate(); const { accept } = useCustomer();
  const [tab,setTab]=useState("login"); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(() => { const token=new URLSearchParams(location.search).get("token"); const code=new URLSearchParams(location.search).get("code"); const oauthError=new URLSearchParams(location.search).get("oauth_error");
    if (oauthError) setError(oauthError === "link_required" ? "An account already uses this email. Sign in with your password before linking Google." : "Google sign-in could not be completed.");
    if (location.pathname === "/verify-email-change" && token) customerApi("/api/customer/email-change/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}).then(async r=>{const d=await r.json();if(r.ok){clearCustomerSession();setMessage(d.message);}else setError(d.message);});
    if (location.pathname === "/verify-email" && token) customerApi("/api/customer/auth/email/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}).then(async r=>{const d=await r.json(); r.ok?setMessage(d.message):setError(d.message);});
    if (location.pathname === "/auth/google/callback" && code) customerApi("/api/customer/auth/google/exchange",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})}).then(async r=>{const d=await r.json(); if(r.ok){accept(d);navigate("/account",{replace:true});}else setError(d.message);});
    if (location.pathname === "/reset-password") setTab("reset");
  }, [location.pathname, location.search]);
  const submit=async(event)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form); if(tab==="register") payload.terms=Boolean(form.get("terms"));
    try{const path=tab==="register"?"register":tab==="forgot"?"forgot-password":tab==="reset"?"reset-password":"login"; if(tab==="reset") payload.token=new URLSearchParams(location.search).get("token"); const r=await customerApi(`/api/customer/auth/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||Object.values(d.errors||{})[0]?.[0]);if(d.token){accept(d);navigate(location.state?.from||"/account");}else setMessage(d.message);}catch(e){setError(e.message||"Unable to continue.");}finally{setBusy(false);}};
  const google=async()=>{setBusy(true);const r=await customerApi("/api/customer/auth/google/redirect");const d=await r.json();if(r.ok)window.location.assign(d.url);else{setError(d.message);setBusy(false);}};
  return <PublicPageLayout eyebrow="Customer account" title="Your Climoraone account" description="Orders, invoices and thoughtful recommendations in one secure place." className="customer-page"><section className="customer-auth-card"><div className="customer-auth-tabs"><button className={tab==="login"?"active":""} onClick={()=>setTab("login")}>Sign In</button><button className={tab==="register"?"active":""} onClick={()=>setTab("register")}>Create Account</button></div>{error&&<div className="customer-alert error">{error}</div>}{message&&<div className="customer-alert success">{message}</div>}
    <form onSubmit={submit} className="customer-form">{tab==="register"&&<><label>Full name<input name="name" required minLength="2" /></label><label>Email address<input name="email" type="email" required /></label><label>Mobile number <small>Optional; not available for login yet</small><input name="phone" inputMode="tel" /></label></>}{(tab==="login")&&<label>Email address<input name="identifier" required /></label>}{tab==="forgot"&&<label>Email address<input name="email" type="email" required /></label>}{tab==="reset"&&<><label>New password<input name="password" type="password" required /></label><label>Confirm password<input name="password_confirmation" type="password" required /></label></>}{["login","register"].includes(tab)&&<><label>Password<input name="password" type="password" required /></label>{tab==="register"&&<><label>Confirm password<input name="password_confirmation" type="password" required /></label><label className="customer-check"><input name="terms" type="checkbox" required /> I agree to the Terms and Privacy Policy</label></>}</>}<button className="customer-primary" disabled={busy}>{busy?"Please wait...":tab==="register"?"Create Account":tab==="forgot"?"Send Reset Link":tab==="reset"?"Reset Password":"Sign In"}</button></form>
    {tab==="login"&&<button className="customer-text-button" onClick={()=>setTab("forgot")}>Forgot password?</button>}{["login","register"].includes(tab)&&<><div className="customer-or">or</div><button className="customer-google" onClick={google} disabled={busy}>Continue with Google</button></>}<Link className="customer-guest" to="/">Continue Shopping as Guest</Link></section></PublicPageLayout>;
}
