import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { customerApi } from "../auth/customerAuth";
import { useCustomer } from "../context/CustomerContext";
import { PublicPageLayout } from "../components/PublicPageLayout";

const tabs={"/account/orders":"orders","/account/profile":"profile","/account/security":"security"};
export default function CustomerAccount(){const location=useLocation();const {customer,setCustomer}=useCustomer();const [tab,setTab]=useState(tabs[location.pathname]||"dashboard");const [orders,setOrders]=useState([]);const [recommendations,setRecommendations]=useState([]);const [summary,setSummary]=useState({});const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState("");const [expanded,setExpanded]=useState("");
 useEffect(()=>setTab(tabs[location.pathname]||"dashboard"),[location.pathname]);
 useEffect(()=>{customerApi("/api/customer/me").then(async r=>{const d=await r.json();if(r.ok){setSummary(d);setCustomer(d.customer);}});if(customer?.email_verified_at){customerApi("/api/customer/orders").then(async r=>{const d=await r.json();if(r.ok)setOrders(d);else setError(d.message);});customerApi("/api/customer/recommendations").then(async r=>{if(r.ok)setRecommendations(await r.json());});}},[]);
 const invoice=async(order,mode)=>{setBusy(`${order.order_number}:${mode}`);setError("");let tabWindow=mode==="view"?window.open("","_blank"):null;try{const r=await customerApi(order.customer_invoice_url);if(!r.ok){const d=await r.json();throw new Error(d.message);}const blob=await r.blob();const url=URL.createObjectURL(blob);if(tabWindow){tabWindow.opener=null;tabWindow.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000);}else{const a=document.createElement("a");a.href=url;a.download=order.invoice_file_name;a.click();URL.revokeObjectURL(url);}}catch(e){tabWindow?.close();setError(e.message);}finally{setBusy("");}};
 const saveProfile=async e=>{e.preventDefault();setError("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await customerApi("/api/customer/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok){setCustomer(d.customer);setMessage(d.message);}else setError(d.message||Object.values(d.errors||{})[0]?.[0]||"Unable to save profile.");};
 const savePassword=async e=>{e.preventDefault();setError("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await customerApi("/api/customer/password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();r.ok?(setMessage(d.message),e.currentTarget.reset()):setError(d.message||Object.values(d.errors||{})[0]?.[0]||"Unable to change password.");};
 const timeline=o=>{let h={};try{h=JSON.parse(o.status_history||"{}");}catch{h={};}return ["Order Received","Confirmed","Packed","Shipped","Out for Delivery","Delivered"].map(s=><li className={h[s]||o.status===s?"done":""} key={s}><span />{s}{h[s]&&<small>{new Date(h[s]).toLocaleString()}</small>}</li>)};
 return <PublicPageLayout eyebrow="My Climoraone" title={`Welcome, ${customer?.name?.split(" ")[0]||"Customer"}`} description="Your purchases support rural women, artisans and traditional craftsmanship." className="customer-page"><nav className="customer-account-tabs"><button onClick={()=>setTab("dashboard")}>Overview</button><button onClick={()=>setTab("orders")}>My Orders</button><button onClick={()=>setTab("profile")}>Profile</button><button onClick={()=>setTab("security")}>Password</button></nav>{error&&<div className="customer-alert error">{error}</div>}{message&&<div className="customer-alert success">{message}</div>}{!customer?.email_verified_at&&<div className="customer-verify-banner">Verify your email to unlock historical orders and sensitive account features.</div>}
 {tab==="dashboard"&&<><div className="customer-metrics"><article><small>Paid orders</small><strong>{summary.order_count||0}</strong></article><article><small>Latest status</small><strong>{summary.latest_order?.status||"No orders yet"}</strong></article><article><small>Email</small><strong>{customer?.email_verified_at?"Verified":"Verification pending"}</strong></article></div><Suggestions products={recommendations}/></>}
 {tab==="orders"&&<section className="customer-orders">{!customer?.email_verified_at?<p>Verify your email before viewing order history.</p>:orders.length===0?<p>No paid orders are linked to this account yet.</p>:orders.map(o=><article className="customer-order-card" key={o.order_number}><header><div><small>{new Date(o.created_at).toLocaleDateString()}</small><h2>{o.order_number}</h2></div><span>{o.status}</span></header><div className="customer-order-summary"><span>Payment <strong>{o.payment_status}</strong></span><span>Items <strong>{o.items.reduce((n,i)=>n+Number(i.quantity),0)}</strong></span><span>Total <strong>₹{o.total}</strong></span></div><div className="customer-order-actions"><button onClick={()=>setExpanded(expanded===o.order_number?"":o.order_number)}>View Details</button>{o.has_invoice&&<><button disabled={!!busy} onClick={()=>invoice(o,"view")}>{busy===`${o.order_number}:view`?"Opening...":"View Invoice"}</button><button disabled={!!busy} onClick={()=>invoice(o,"download")}>{busy===`${o.order_number}:download`?"Downloading...":"Download Invoice"}</button></>}</div>{expanded===o.order_number&&<div className="customer-order-details"><div>{o.items.map(i=><div className="customer-order-item" key={i.id}><span>{i.product_name}</span><span>{i.quantity} × ₹{i.price}</span><strong>₹{i.subtotal}</strong></div>)}</div><p><strong>Ship to:</strong> {o.address}, {o.city}, {o.state} {o.pincode}</p><ol className="customer-timeline">{timeline(o)}</ol></div>}</article>)}</section>}
 {tab==="profile"&&<form className="customer-form customer-panel" onSubmit={saveProfile}><h2>Profile</h2><label>Full name<input name="name" defaultValue={customer?.name} required /></label><label>Username<input name="username" defaultValue={customer?.username||""} minLength="3" pattern="[A-Za-z0-9._-]+" placeholder="Choose a username" /></label><label>Email<input name="email" type="email" defaultValue={customer?.email} required /></label><label>Mobile number <small>Optional</small><input name="phone" defaultValue={customer?.phone||""} placeholder="+91XXXXXXXXXX" /></label><button className="customer-primary">Save Profile</button></form>}
 {tab==="security"&&<form className="customer-form customer-panel" onSubmit={savePassword}><h2>{customer?.has_password===false?"Create Password":"Change Password"}</h2>{customer?.has_password!==false&&<label>Current password<input name="current_password" type="password" required /></label>}<label>New password<input name="password" type="password" required /></label><label>Confirm password<input name="password_confirmation" type="password" required /></label><button className="customer-primary">Save Password</button></form>}</PublicPageLayout>}

function Suggestions({products}){return <section className="customer-suggestions"><h2>Selected for you</h2><div>{products.map(p=><article key={p.id}>{p.main_image?<img src={p.main_image} alt={p.name}/>:<div className="customer-suggestion-placeholder" aria-hidden="true">Climoraone</div>}<small>{p.category}</small><h3>{p.name}</h3><strong>₹{p.price}</strong></article>)}</div></section>}
